networks:
  net-pnet:

services:
  dg:
    build: .
    restart: unless-stopped
    networks:
      - net-pnet
    ports:
      - "7777:7777/udp"
      - "8777:8777/tcp"
    volumes:
      - /opt/pnet:/root/.pnet

  deliverer:
    build:
      context: .
      dockerfile: apps/pnet_deliverer/Dockerfile
    restart: unless-stopped
    networks:
      - net-pnet
    environment:
      - PNET_ADDR=dg:7777
    ports:
      - "3000:3000/tcp"
    volumes:
      - /opt/pnet-deliverer:/app
    depends_on:
      - dg

