networks:
  net-william:
  net-chad:
  net-sg-backbone:

services:
  sg-william:
    build: .
    restart: unless-stopped
    networks:
      - net-william
      - net-sg-backbone
    ports:
      - "7777:7777/udp"
      - "8777:8777/tcp"
    environment:
      - PNET_HOSTS=pnet.thehomegarage.com:7777,sg-william
    volumes:
      - /opt/pnet/william:/root/.pnet

  deliverer-william:
    build:
      context: .
      dockerfile: apps/pnet_deliverer/Dockerfile
    restart: unless-stopped
    networks:
      - net-william
    environment:
      - PNET_ADDR=sg-william:7777
    ports:
      - "3000:3000/tcp"
    volumes:
      - /opt/pnet-deliverer/william:/app
    depends_on:
      - sg-william

  sg-chad:
    build: .
    restart: unless-stopped
    networks:
      - net-chad
      - net-sg-backbone
    ports:
      - "7778:7777/udp"
      - "8778:8777/tcp"
    environment:
      - PNET_HOSTS=pnet.thehomegarage.com:7778,sg-chad
    volumes:
      - /opt/pnet/chad:/root/.pnet

  deliverer-chad:
    build:
      context: .
      dockerfile: apps/pnet_deliverer/Dockerfile
    restart: unless-stopped
    networks:
      - net-chad
    environment:
      - PNET_ADDR=sg-chad:7777
    ports:
      - "3001:3000/tcp"
    volumes:
      - /opt/pnet-deliverer/chad:/app
    depends_on:
      - sg-chad
